language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3.1
  - DJANGO=1.4.1
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - pep8 --ignore=E501 gaiarestframework
  - pyflakes -x W gaiarestframework
