language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -q -e . --use-mirrors
before_script:
  - pip install -q -r test_requirements.txt --use-mirrors
script:
  - pep8 --ignore=E501 --exclude=example gaiarestframework
  - python gaiarestframework/example/manage.py test library
